name: qa
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - accelerate=1.2.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.3=py312h06a4308_0
  - aiohttp=3.10.5=py312h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - altair=5.0.1=py312h06a4308_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - attrs=24.2.0=py312h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - blas=1.0=mkl
  - blinker=1.6.2=py312h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.11.26=h06a4308_0
  - cachetools=5.3.3=py312h06a4308_0
  - certifi=2024.8.30=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py312h06a4308_0
  - colorama=0.4.6=py312h06a4308_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - datasets=2.19.1=py312h06a4308_0
  - dill=0.3.8=py312h06a4308_0
  - english=2020.7.0=pyhd8ed1ab_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.5.0=py312h5eee18b_0
  - fsspec=2024.3.1=py312h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py312h06a4308_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - h11=0.14.0=py312h06a4308_0
  - huggingface_hub=0.24.6=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - interchange=2021.0.4=pyhd8ed1ab_0
  - jinja2=3.1.4=py312h06a4308_1
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jsonschema=4.23.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.2.0=h77fa898_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py312h06a4308_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - mdurl=0.1.0=py312h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - monotonic=1.5=py_0
  - mpmath=1.3.0=py312h06a4308_0
  - multidict=6.1.0=py312h5eee18b_0
  - multiprocess=0.70.15=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - neobolt=1.7.17=py312h98912ed_6
  - neotime=1.7.4=py312h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py312h06a4308_0
  - numexpr=2.10.1=py312h3c60e43_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.4.0=hb9d3cd8_0
  - orc=2.0.1=h2d29ad5_0
  - outcome=1.1.0=pyhd3eb1b0_0
  - packaging=24.1=py312h06a4308_0
  - pandas=2.2.2=py312h526ad5a_0
  - pillow=11.0.0=py312hfdbf927_0
  - pip=24.2=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - propcache=0.2.0=py312h5eee18b_0
  - protobuf=4.25.3=py312h12ddb61_0
  - psutil=5.9.0=py312h5eee18b_0
  - py2neo=2021.2.3=pyhd8ed1ab_0
  - pyarrow=16.1.0=py312h526ad5a_0
  - pydeck=0.8.0=py312h06a4308_2
  - pygments=2.15.1=py312h06a4308_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-dotenv=0.21.0=py312h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py312h5eee18b_1
  - python_abi=3.12=5_cp312
  - pytorch=2.5.1=py3.12_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - regex=2024.9.11=py312h5eee18b_0
  - requests=2.32.3=py312h06a4308_0
  - rich=13.9.4=py312h06a4308_0
  - rpds-py=0.10.6=py312h4aa5aa6_1
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.4.5=py312hc50d6dc_1
  - scikit-learn=1.5.1=py312h526ad5a_0
  - scipy=1.14.1=py312hc5e2394_0
  - selenium=4.24.0=py312hb02cf49_0
  - setuptools=75.1.0=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py312h06a4308_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.45.3=h5eee18b_0
  - streamlit=1.40.1=py312h06a4308_0
  - sympy=1.13.2=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=9.0.0=py312h06a4308_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.21.0=py312h8360d73_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py312h06a4308_0
  - torchaudio=2.5.1=py312_cu118
  - torchtriton=3.1.0=py312
  - torchvision=0.20.1=py312_cu118
  - tornado=6.4.1=py312h5eee18b_0
  - tqdm=4.66.5=py312he106c6f_0
  - transformers=4.47.0=pyhd8ed1ab_0
  - trio=0.26.2=py312h06a4308_0
  - trio-websocket=0.11.1=py312h06a4308_0
  - typing-extensions=4.11.0=py312h06a4308_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - urllib3=2.2.3=py312h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - watchdog=4.0.1=py312h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webdriver-manager=4.0.2=pyhd8ed1ab_0
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.44.0=py312h06a4308_0
  - wsproto=1.2.0=py312h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py312h5eee18b_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - modelscope==1.21.0
prefix: /your/path/to/anaconda3/envs/qa
